# Generated by Django 4.2.4 on 2023-08-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, height_field=75, upload_to='product', width_field=100),
        ),
    ]
